name: Deploy

on: [push, workflow_dispatch]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
  OPENMAPTILES_KEY: ${{ secrets.OPENMAPTILES_KEY }}
  AZURE_MAPS_KEY: ${{ secrets.AZURE_MAPS_KEY }}
  S3_BUCKET: city-bureau-projects
  GOOGLE_ANALYTICS_ID: UA-68381272-6

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [checks]
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod')
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - run: npm ci --prefer-offline --no-audit --no-optional

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - run: npm run build

      - run: make deploy-site
